site_name: Beekeeper
# repo_url: https://github.com/beekeeper-ai/beekeeper

markdown_extensions:
  - toc:
      title: "On this page"
      permalink: "#"
      toc_depth: 4
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - md_in_html

extra:
  version: "2.0.0"
extra_css:
  - _static/css/style.css

docs_dir: api_reference

plugins:
  - search
  - include_dir_to_nav
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            separate_signature: true
            merge_init_into_class: true
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            heading_level: 2
            members_order: source
            show_signature_annotations: true
            show_root_toc_entry: false
          paths:
            - ../../beekeeper-core/
            - ../../beekeeper-integrations/embedding/huggingface
            - ../../beekeeper-integrations/embedding/watsonx
            - ../../beekeeper-integrations/guardrail/watsonx
            - ../../beekeeper-integrations/llm/litellm
            - ../../beekeeper-integrations/llm/watsonx
            - ../../beekeeper-integrations/observability/watsonx
            - ../../beekeeper-integrations/loader/docling
            - ../../beekeeper-integrations/loader/file
            - ../../beekeeper-integrations/loader/ibm_cos
            - ../../beekeeper-integrations/loader/watson_discovery
            - ../../beekeeper-integrations/retriever/watson_discovery
            - ../../beekeeper-integrations/vector_store/chroma
            - ../../beekeeper-integrations/vector_store/elasticsearch

nav:
  - API Reference: index.md
  # - Getting Started:
  #   - Installation: getting-started/installation.md
  - Embedding: embedding/
  - Evaluation: evaluation/
  - Guardrail: guardrail/
  - LLM: llm/
  - Observability: observability/
  - Prompt: prompt/
  - Loader: loader/
  - Retriever: retriever/
  - Text Chunker: text_chunker/
  - Vector Store: vector_store/
  - Workflow: workflow/

theme:
  name: material
  custom_dir: overrides
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: white
      accent: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: black
      accent: purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - navigation.tabs
    # - navigation.sections
    - navigation.instant        
    - navigation.indexes        
    - navigation.top                    
    - navigation.tracking
    - search.highlight
    - content.code.copy
    - toc.follow
